// useDispatch is for to call all the actionCreators functions/ minor reducers
// useSelector is used to access all the state value present in the redux store
import { useDispatch, useSelector } from "react-redux";
// to generate random movie name path = data/index.js
import { createRandomMovie } from "../data";
//path = store/index.js
import { addMovie, removeMovie } from "../store";

function MoviePlaylist() {
  // useDispatch hook is used to call all the action creator functions/minor reducers
  const dispatch = useDispatch();
  // moviesPlaylist after using useSelector() become an array of autogenerated movies name
  const moviePlaylist = useSelector((state) => {
    // paste all movies array state data to moviePlaylist variable
    return state.movies;
  });

  // handleMovieAdd function is used to add movie to moviePlaylist
  const handleMovieAdd = (movie) => {
    dispatch(addMovie(movie));
  };
  // handleMovieRemove function is used to remove movie from moviePlaylist
  const handleMovieRemove = (movie) => {
    dispatch(removeMovie(movie));
  };

  const renderedMovies = moviePlaylist.map((movie) => {
    return (
      <li key={movie}>
        {movie}
        <button
          onClick={() => handleMovieRemove(movie)}
          className='button is-danger'
        >
          X
        </button>
      </li>
    );
  });

  return (
    <div className='content'>
      <div className='table-header'>
        <h3 className='subtitle is-3'>Movie Playlist</h3>
        <div className='buttons'>
          <button
            onClick={() => handleMovieAdd(createRandomMovie())}
            className='button is-link'
          >
            + Add Movie to Playlist
          </button>
        </div>
      </div>
      <ul>{renderedMovies}</ul>
    </div>
  );
}

export default MoviePlaylist;
